import './globals.css';

export const metadata = {
  title: 'Spotify - Reproductor web',
  description: 'Generated by Replica de Spotify',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-spotify-black'>{children}</body>
    </html>
  )
}
